// preload — 桥梁世界：只做转发，零业务逻辑（桥越薄，换壳越便宜）。
// invoke = 请求/响应；on = 订阅，返回退订函数（不退订 = 监听器泄漏）。

import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";
import { CHANNELS, type ShellBridge, type Unsubscribe } from "../shared/shellBridge.js";

function subscribe<T>(channel: string) {
  return (cb: (payload: T) => void): Unsubscribe => {
    const listener = (_e: IpcRendererEvent, payload: T) => cb(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  };
}

const bridge: ShellBridge = {
  boot: () => ipcRenderer.invoke(CHANNELS.boot),
  pickWorkspace: () => ipcRenderer.invoke(CHANNELS.pickWorkspace),
  startSession: (opts) => ipcRenderer.invoke(CHANNELS.startSession, opts),
  listSessions: () => ipcRenderer.invoke(CHANNELS.listSessions),
  resumeSession: (sessionId) => ipcRenderer.invoke(CHANNELS.resumeSession, sessionId),
  readSessionEvents: (sessionId) => ipcRenderer.invoke(CHANNELS.readSessionEvents, sessionId),
  startSideSession: (fromSessionId) => ipcRenderer.invoke(CHANNELS.startSideSession, fromSessionId),
  liveBackgroundTasks: (sessionId) => ipcRenderer.invoke(CHANNELS.liveBackgroundTasks, sessionId),
  residueList: (sessionId) => ipcRenderer.invoke(CHANNELS.residueList, sessionId),
  residueClean: (sessionId, itemIds) => ipcRenderer.invoke(CHANNELS.residueClean, sessionId, itemIds),
  deleteSession: (sessionId) => ipcRenderer.invoke(CHANNELS.deleteSession, sessionId),
  archiveSession: (sessionId) => ipcRenderer.invoke(CHANNELS.archiveSession, sessionId),
  unarchiveSession: (sessionId) => ipcRenderer.invoke(CHANNELS.unarchiveSession, sessionId),
  renameSession: (sessionId, title) => ipcRenderer.invoke(CHANNELS.renameSession, sessionId, title),
  setSessionTopic: (sessionId, topic) => ipcRenderer.invoke(CHANNELS.setSessionTopic, sessionId, topic),
  rewindToCheckpoint: (sessionId, checkpointSeq) =>
    ipcRenderer.invoke(CHANNELS.rewindToCheckpoint, sessionId, checkpointSeq),
  switchModel: (model, lane) => ipcRenderer.invoke(CHANNELS.switchModel, model, lane),
  setApprovalMode: (sessionId, mode) => ipcRenderer.invoke(CHANNELS.setApprovalMode, sessionId, mode),
  setThinking: (sessionId, mode) => ipcRenderer.invoke(CHANNELS.setThinking, sessionId, mode),
  listPermissions: () => ipcRenderer.invoke(CHANNELS.listPermissions),
  revokeGrant: (key) => ipcRenderer.invoke(CHANNELS.revokeGrant, key),
  removeExecRule: (rule) => ipcRenderer.invoke(CHANNELS.removeExecRule, rule),
  listSkills: () => ipcRenderer.invoke(CHANNELS.listSkills),
  listExternalSkills: () => ipcRenderer.invoke(CHANNELS.listExternalSkills),
  importSkills: (names) => ipcRenderer.invoke(CHANNELS.importSkills, names),
  releaseSkill: (sessionId, name) => ipcRenderer.invoke(CHANNELS.releaseSkill, sessionId, name),
  getMemory: () => ipcRenderer.invoke(CHANNELS.getMemory),
  saveMemory: (target, text, sessionId, projectRoot, topic) =>
    ipcRenderer.invoke(CHANNELS.saveMemory, target, text, sessionId, projectRoot, topic),
  forgetMemory: (target, entry, sessionId, projectRoot, topic) =>
    ipcRenderer.invoke(CHANNELS.forgetMemory, target, entry, sessionId, projectRoot, topic),
  listProjectMemories: () => ipcRenderer.invoke(CHANNELS.listProjectMemories),
  deleteProjectMemory: (root) => ipcRenderer.invoke(CHANNELS.deleteProjectMemory, root),
  listTopicMemories: () => ipcRenderer.invoke(CHANNELS.listTopicMemories),
  deleteTopicMemory: (slug) => ipcRenderer.invoke(CHANNELS.deleteTopicMemory, slug),
  setTopicLabel: (slug, label) => ipcRenderer.invoke(CHANNELS.setTopicLabel, slug, label),
  rebuildSearchIndex: () => ipcRenderer.invoke(CHANNELS.rebuildSearchIndex),
  searchIndex: (query) => ipcRenderer.invoke(CHANNELS.searchIndex, query),
  getAutoCompact: () => ipcRenderer.invoke(CHANNELS.getAutoCompact),
  setAutoCompact: (settings) => ipcRenderer.invoke(CHANNELS.setAutoCompact, settings),
  getHelperModel: () => ipcRenderer.invoke(CHANNELS.getHelperModel),
  setHelperModel: (model) => ipcRenderer.invoke(CHANNELS.setHelperModel, model),
  getVisionModel: () => ipcRenderer.invoke(CHANNELS.getVisionModel),
  setVisionModel: (model) => ipcRenderer.invoke(CHANNELS.setVisionModel, model),
  remoteStatus: () => ipcRenderer.invoke(CHANNELS.remoteStatus),
  remotePairDevice: (deviceId) => ipcRenderer.invoke(CHANNELS.remotePairDevice, deviceId),
  remoteStartPairing: () => ipcRenderer.invoke(CHANNELS.remoteStartPairing),
  remoteCancelPairing: () => ipcRenderer.invoke(CHANNELS.remoteCancelPairing),
  remoteUnpairDevice: (deviceId) => ipcRenderer.invoke(CHANNELS.remoteUnpairDevice, deviceId),
  remoteForgetDevice: (deviceId) => ipcRenderer.invoke(CHANNELS.remoteForgetDevice, deviceId),
  getIslandSettings: () => ipcRenderer.invoke(CHANNELS.getIslandSettings),
  setIslandSettings: (settings) => ipcRenderer.invoke(CHANNELS.setIslandSettings, settings),
  getMotionSettings: () => ipcRenderer.invoke(CHANNELS.getMotionSettings),
  setMotionSettings: (settings) => ipcRenderer.invoke(CHANNELS.setMotionSettings, settings),
  getWorkspaceSettings: () => ipcRenderer.invoke(CHANNELS.getWorkspaceSettings),
  setDefaultWorkspace: (dir) => ipcRenderer.invoke(CHANNELS.setDefaultWorkspace, dir),
  updaterGetState: () => ipcRenderer.invoke(CHANNELS.updaterGetState),
  updaterCheckNow: () => ipcRenderer.invoke(CHANNELS.updaterCheckNow),
  updaterStartDownload: () => ipcRenderer.invoke(CHANNELS.updaterStartDownload),
  updaterInstallAndRestart: () => ipcRenderer.invoke(CHANNELS.updaterInstallAndRestart),
  updaterOpenReleasePage: () => ipcRenderer.invoke(CHANNELS.updaterOpenReleasePage),
  onUpdaterState: subscribe(CHANNELS.updaterState),
  listMcpServers: () => ipcRenderer.invoke(CHANNELS.listMcpServers),
  saveMcpServer: (id, cfg) => ipcRenderer.invoke(CHANNELS.saveMcpServer, id, cfg),
  searchMcpRegistry: (query) => ipcRenderer.invoke(CHANNELS.searchMcpRegistry, query),
  removeMcpServer: (id) => ipcRenderer.invoke(CHANNELS.removeMcpServer, id),
  reconnectMcpServer: (id) => ipcRenderer.invoke(CHANNELS.reconnectMcpServer, id),
  authorizeMcpServer: (id) => ipcRenderer.invoke(CHANNELS.authorizeMcpServer, id),
  listMcpPrompts: () => ipcRenderer.invoke(CHANNELS.listMcpPrompts),
  expandMcpPrompt: (server, name, args) =>
    ipcRenderer.invoke(CHANNELS.expandMcpPrompt, server, name, args),
  toolCatalog: () => ipcRenderer.invoke(CHANNELS.toolCatalog),
  listSubagents: (workspace) => ipcRenderer.invoke(CHANNELS.listSubagents, workspace),
  saveSubagent: (def, workspace) => ipcRenderer.invoke(CHANNELS.saveSubagent, def, workspace),
  createSubagent: (name, workspace) => ipcRenderer.invoke(CHANNELS.createSubagent, name, workspace),
  protocolListAdrs: (repoDir) => ipcRenderer.invoke(CHANNELS.protocolListAdrs, repoDir),
  protocolReadAdr: (repoDir, relPath) => ipcRenderer.invoke(CHANNELS.protocolReadAdr, repoDir, relPath),
  protocolListIssues: (repoDir) => ipcRenderer.invoke(CHANNELS.protocolListIssues, repoDir),
  protocolGetIssue: (repoDir, number) => ipcRenderer.invoke(CHANNELS.protocolGetIssue, repoDir, number),
  gitGraphLog: (repoDir, limit) => ipcRenderer.invoke(CHANNELS.gitGraphLog, repoDir, limit),
  gitGraphCommit: (repoDir, hash) => ipcRenderer.invoke(CHANNELS.gitGraphCommit, repoDir, hash),
  gitBranches: (repoDir) => ipcRenderer.invoke(CHANNELS.gitBranches, repoDir),
  gitCheckout: (repoDir, branch, sessionId) =>
    ipcRenderer.invoke(CHANNELS.gitCheckout, repoDir, branch, sessionId),
  gitStatus: (repoDir) => ipcRenderer.invoke(CHANNELS.gitStatus, repoDir),
  mergeIsolated: (sessionId) => ipcRenderer.invoke(CHANNELS.mergeIsolated, sessionId),
  filesList: (root, relDir) => ipcRenderer.invoke(CHANNELS.filesList, root, relDir),
  filesSearch: (root, query, opts) => ipcRenderer.invoke(CHANNELS.filesSearch, root, query, opts),
  filesRead: (root, rel) => ipcRenderer.invoke(CHANNELS.filesRead, root, rel),
  filesReveal: (root, rel, how, appName) =>
    ipcRenderer.invoke(CHANNELS.filesReveal, root, rel, how, appName),
  filesEditors: () => ipcRenderer.invoke(CHANNELS.filesEditors),
  setPresenceWorkspace: (repoDir) => ipcRenderer.invoke(CHANNELS.setPresenceWorkspace, repoDir),
  terminalList: (sessionId) => ipcRenderer.invoke(CHANNELS.terminalList, sessionId),
  terminalOpen: (sessionId, cols, rows) => ipcRenderer.invoke(CHANNELS.terminalOpen, sessionId, cols, rows),
  terminalAttach: (id) => ipcRenderer.invoke(CHANNELS.terminalAttach, id),
  terminalInput: (id, data) => ipcRenderer.invoke(CHANNELS.terminalInput, id, data),
  terminalResize: (id, cols, rows) => ipcRenderer.invoke(CHANNELS.terminalResize, id, cols, rows),
  terminalClose: (id) => ipcRenderer.invoke(CHANNELS.terminalClose, id),
  browserOpen: (sessionId) => ipcRenderer.invoke(CHANNELS.browserOpen, sessionId),
  browserNavigate: (sessionId, url) => ipcRenderer.invoke(CHANNELS.browserNavigate, sessionId, url),
  browserSetBounds: (sessionId, bounds) => ipcRenderer.invoke(CHANNELS.browserSetBounds, sessionId, bounds),
  browserBack: (sessionId) => ipcRenderer.invoke(CHANNELS.browserBack, sessionId),
  browserForward: (sessionId) => ipcRenderer.invoke(CHANNELS.browserForward, sessionId),
  browserReload: (sessionId) => ipcRenderer.invoke(CHANNELS.browserReload, sessionId),
  browserClose: (sessionId) => ipcRenderer.invoke(CHANNELS.browserClose, sessionId),
  browserPickElement: (sessionId) => ipcRenderer.invoke(CHANNELS.browserPickElement, sessionId),
  browserCancelPick: (sessionId) => ipcRenderer.invoke(CHANNELS.browserCancelPick, sessionId),
  simState: () => ipcRenderer.invoke(CHANNELS.simState),
  simSelect: (udid) => ipcRenderer.invoke(CHANNELS.simSelect, udid),
  simBoot: (udid) => ipcRenderer.invoke(CHANNELS.simBoot, udid),
  simShutdown: (udid) => ipcRenderer.invoke(CHANNELS.simShutdown, udid),
  simStartStream: () => ipcRenderer.invoke(CHANNELS.simStartStream),
  simStopStream: () => ipcRenderer.invoke(CHANNELS.simStopStream),
  simTap: (x, y) => ipcRenderer.invoke(CHANNELS.simTap, x, y),
  simSwipe: (x, y, x2, y2, durationMs) => ipcRenderer.invoke(CHANNELS.simSwipe, x, y, x2, y2, durationMs),
  simType: (text) => ipcRenderer.invoke(CHANNELS.simType, text),
  simButton: (button) => ipcRenderer.invoke(CHANNELS.simButton, button),
  simRequestInputPermission: () => ipcRenderer.invoke(CHANNELS.simRequestInputPermission),
  intakePastedFiles: (files) => ipcRenderer.invoke(CHANNELS.intakePastedFiles, files),
  getAccount: () => ipcRenderer.invoke(CHANNELS.getAccount),
  hasAuthRecord: () => ipcRenderer.invoke(CHANNELS.hasAuthRecord),
  configRoot: () => ipcRenderer.invoke(CHANNELS.configRoot),
  usageByProvider: (days: number) => ipcRenderer.invoke(CHANNELS.usageByProvider, days),
  providerBalances: () => ipcRenderer.invoke(CHANNELS.providerBalances),
  billingSnapshot: (refresh) => ipcRenderer.invoke(CHANNELS.billingSnapshot, refresh),
  billingCheckout: (target) => ipcRenderer.invoke(CHANNELS.billingCheckout, target),
  billingPortal: () => ipcRenderer.invoke(CHANNELS.billingPortal),
  signIn: (provider) => ipcRenderer.invoke(CHANNELS.signIn, provider),
  signInWithPassword: (email, password) => ipcRenderer.invoke(CHANNELS.signInWithPassword, email, password),
  signUpWithPassword: (email, password, name) => ipcRenderer.invoke(CHANNELS.signUpWithPassword, email, password, name),
  resetPassword: (email) => ipcRenderer.invoke(CHANNELS.resetPassword, email),
  verifyRecoveryOtp: (email, token) => ipcRenderer.invoke(CHANNELS.verifyRecoveryOtp, email, token),
  updatePassword: (password) => ipcRenderer.invoke(CHANNELS.updatePassword, password),
  signOut: () => ipcRenderer.invoke(CHANNELS.signOut),
  myProfile: () => ipcRenderer.invoke(CHANNELS.myProfile),
  updateProfile: (patch) => ipcRenderer.invoke(CHANNELS.updateProfile, patch),
  keyStatus: () => ipcRenderer.invoke(CHANNELS.keyStatus),
  setApiKey: (envName, key) => ipcRenderer.invoke(CHANNELS.setApiKey, envName, key),
  openProviderConsole: (providerId) => ipcRenderer.invoke(CHANNELS.openProviderConsole, providerId),
  listOllamaModels: () => ipcRenderer.invoke(CHANNELS.listOllamaModels),
  sendMessage: (sessionId, text, skill, attachments, skillArgs) =>
    ipcRenderer.invoke(CHANNELS.sendMessage, sessionId, text, skill, attachments, skillArgs),
  pickAttachments: () => ipcRenderer.invoke(CHANNELS.pickAttachments),
  attachmentDataUrl: (id) => ipcRenderer.invoke(CHANNELS.attachmentDataUrl, id),
  stopTurn: (sessionId) => ipcRenderer.invoke(CHANNELS.stopTurn, sessionId),
  steerTurn: (sessionId, text, expectedTurnId) =>
    ipcRenderer.invoke(CHANNELS.steerTurn, sessionId, text, expectedTurnId),
  compact: (sessionId) => ipcRenderer.invoke(CHANNELS.compact, sessionId),
  decideApproval: (sessionId, toolCallId, outcome) =>
    ipcRenderer.invoke(CHANNELS.decideApproval, sessionId, toolCallId, outcome),
  answerQuestions: (sessionId, toolCallId, outcome) =>
    ipcRenderer.invoke(CHANNELS.answerQuestions, sessionId, toolCallId, outcome),
  sessionRuntime: (sessionId) => ipcRenderer.invoke(CHANNELS.sessionRuntime, sessionId),
  onEvent: subscribe(CHANNELS.event),
  onApprovalRequest: subscribe(CHANNELS.approvalRequest),
  onAskUserRequest: subscribe(CHANNELS.askUserRequest),
  onTurnStatus: subscribe(CHANNELS.turnStatus),
  onTurnDiff: subscribe(CHANNELS.turnDiff),
  onAssistantDelta: subscribe(CHANNELS.assistantDelta),
  onToolOutput: subscribe(CHANNELS.toolOutput),
  onBgTaskOutput: subscribe(CHANNELS.bgTaskOutput),
  onTerminalData: subscribe(CHANNELS.terminalData),
  onTerminalExit: subscribe(CHANNELS.terminalExit),
  onBrowserState: subscribe(CHANNELS.browserState),
  onSimState: subscribe(CHANNELS.simStatePush),
  onSimFrame: subscribe(CHANNELS.simFrame),
  onMcpChanged: subscribe(CHANNELS.mcpChanged),
  onToolDefsChanged: subscribe(CHANNELS.toolDefsChanged),
  onAccountChanged: subscribe(CHANNELS.accountChanged),
  onBillingChanged: subscribe(CHANNELS.billingChanged),
  friendsSearch: (query) => ipcRenderer.invoke(CHANNELS.friendsSearch, query),
  friendsSendRequest: (userId) => ipcRenderer.invoke(CHANNELS.friendsSendRequest, userId),
  friendsRespond: (friendshipId, accept) =>
    ipcRenderer.invoke(CHANNELS.friendsRespond, friendshipId, accept),
  friendsRemove: (friendshipId) => ipcRenderer.invoke(CHANNELS.friendsRemove, friendshipId),
  friendsList: () => ipcRenderer.invoke(CHANNELS.friendsList),
  friendsSendMessage: (friendId, body) =>
    ipcRenderer.invoke(CHANNELS.friendsSendMessage, friendId, body),
  friendsListMessages: (friendId, beforeId) =>
    ipcRenderer.invoke(CHANNELS.friendsListMessages, friendId, beforeId),
  shareSessionToFriend: (sessionId, friendUid, message, title, model, grant) =>
    ipcRenderer.invoke(CHANNELS.shareSessionToFriend, sessionId, friendUid, message, title, model, grant ?? null),
  importSharedSession: (prefix, workspace, grant) =>
    ipcRenderer.invoke(CHANNELS.importSharedSession, prefix, workspace, grant ?? null),
  proxyCreateInvite: (friendUid, allow, ttlMs) =>
    ipcRenderer.invoke(CHANNELS.proxyCreateInvite, friendUid, allow, ttlMs),
  proxyAcceptInvite: (invite, ttlMs) =>
    ipcRenderer.invoke(CHANNELS.proxyAcceptInvite, invite, ttlMs),
  proxyListGrants: () =>
    ipcRenderer.invoke(CHANNELS.proxyListGrants),
  proxyRevoke: (friendUid) =>
    ipcRenderer.invoke(CHANNELS.proxyRevoke, friendUid),
  proxyAudit: (friendUid) =>
    ipcRenderer.invoke(CHANNELS.proxyAudit, friendUid),
  proxyStatus: () =>
    ipcRenderer.invoke(CHANNELS.proxyStatus),
  proxyUpdateGrant: (friendUid, allow) =>
    ipcRenderer.invoke(CHANNELS.proxyUpdateGrant, friendUid, allow),
  proxyDisconnect: (hostUid) =>
    ipcRenderer.invoke(CHANNELS.proxyDisconnect, hostUid),
  workspaceList: () => ipcRenderer.invoke(CHANNELS.workspaceList),
  workspaceCreate: (name) => ipcRenderer.invoke(CHANNELS.workspaceCreate, name),
  workspaceDelete: (id) => ipcRenderer.invoke(CHANNELS.workspaceDelete, id),
  workspaceAddMember: (id, uid) => ipcRenderer.invoke(CHANNELS.workspaceAddMember, id, uid),
  workspaceRemoveMember: (id, uid) => ipcRenderer.invoke(CHANNELS.workspaceRemoveMember, id, uid),
  workspaceLeave: (id) => ipcRenderer.invoke(CHANNELS.workspaceLeave, id),
  workspaceContributeConnector: (id, serverId, tools) =>
    ipcRenderer.invoke(CHANNELS.workspaceContributeConnector, id, serverId, tools),
  workspaceWithdrawConnector: (id, serverId) =>
    ipcRenderer.invoke(CHANNELS.workspaceWithdrawConnector, id, serverId),
  workspacePublishSession: (id, sessionId, title) =>
    ipcRenderer.invoke(CHANNELS.workspacePublishSession, id, sessionId, title),
  workspaceUnpublishSession: (id, rowId) =>
    ipcRenderer.invoke(CHANNELS.workspaceUnpublishSession, id, rowId),
  workspaceImportSession: (publisherUid, pkgId) =>
    ipcRenderer.invoke(CHANNELS.workspaceImportSession, publisherUid, pkgId),
  workspaceCloudList: (workspaceId) => ipcRenderer.invoke(CHANNELS.workspaceCloudList, workspaceId),
  workspaceCloudCreate: (workspaceId) => ipcRenderer.invoke(CHANNELS.workspaceCloudCreate, workspaceId),
  workspaceCloudJoin: (workspaceId, sessionId) =>
    ipcRenderer.invoke(CHANNELS.workspaceCloudJoin, workspaceId, sessionId),
  workspaceCloudLeave: () => ipcRenderer.invoke(CHANNELS.workspaceCloudLeave),
  workspaceCloudSay: (text, mention) => ipcRenderer.invoke(CHANNELS.workspaceCloudSay, text, mention),
  workspaceCloudApprove: (callId, decision) =>
    ipcRenderer.invoke(CHANNELS.workspaceCloudApprove, callId, decision),
  workspaceCloudArchive: () => ipcRenderer.invoke(CHANNELS.workspaceCloudArchive),
  workspaceCloudConfig: (workspaceId, patch) =>
    ipcRenderer.invoke(CHANNELS.workspaceCloudConfig, workspaceId, patch),
  setBadgeCount: (count) => ipcRenderer.invoke(CHANNELS.setBadgeCount, count),
  onFriendsChanged: subscribe(CHANNELS.friendsChanged),
  onProxyChanged: subscribe(CHANNELS.proxyChanged),
  onPresenceChanged: subscribe(CHANNELS.presenceChanged),
  onWorkspacesChanged: subscribe(CHANNELS.workspacesChanged),
  onCloudSessionEvent: subscribe(CHANNELS.cloudSessionEvent),
  onCloudSessionStatus: subscribe(CHANNELS.cloudSessionStatus),
  onDirectMessage: subscribe(CHANNELS.directMessage),
  onRealtimeHealth: subscribe(CHANNELS.realtimeHealth),
  onNotificationActivated: subscribe(CHANNELS.notificationActivated),
  onPlaySound: subscribe(CHANNELS.playSound),
  onIslandFocusSession: subscribe(CHANNELS.islandFocusSession),
  getWindowFullscreen: () => ipcRenderer.invoke(CHANNELS.getWindowFullscreen),
  onWindowFullscreen: subscribe(CHANNELS.windowFullscreen),
  setActiveSession: (sessionId) => ipcRenderer.invoke(CHANNELS.setActiveSession, sessionId),
};

contextBridge.exposeInMainWorld("otter", bridge);
