// preload — 桥梁世界：只做转发，零业务逻辑（桥越薄，换壳越便宜）。
// invoke = 请求/响应；on = 订阅，返回退订函数（不退订 = 监听器泄漏）。

import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";
import { CHANNELS, type ShellBridge, type Unsubscribe } from "../shared/shellBridge.js";

function subscribe<T>(channel: string) {
  return (cb: (payload: T) => void): Unsubscribe => {
    const listener = (_e: IpcRendererEvent, payload: T) => cb(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  };
}

const bridge: ShellBridge = {
  boot: () => ipcRenderer.invoke(CHANNELS.boot),
  pickWorkspace: () => ipcRenderer.invoke(CHANNELS.pickWorkspace),
  startSession: (opts) => ipcRenderer.invoke(CHANNELS.startSession, opts),
  listSessions: () => ipcRenderer.invoke(CHANNELS.listSessions),
  resumeSession: (sessionId) => ipcRenderer.invoke(CHANNELS.resumeSession, sessionId),
  readSessionEvents: (sessionId) => ipcRenderer.invoke(CHANNELS.readSessionEvents, sessionId),
  deleteSession: (sessionId) => ipcRenderer.invoke(CHANNELS.deleteSession, sessionId),
  renameSession: (sessionId, title) => ipcRenderer.invoke(CHANNELS.renameSession, sessionId, title),
  switchModel: (model, lane) => ipcRenderer.invoke(CHANNELS.switchModel, model, lane),
  setApprovalMode: (sessionId, mode) => ipcRenderer.invoke(CHANNELS.setApprovalMode, sessionId, mode),
  setThinking: (sessionId, mode) => ipcRenderer.invoke(CHANNELS.setThinking, sessionId, mode),
  listSkills: () => ipcRenderer.invoke(CHANNELS.listSkills),
  getMemory: () => ipcRenderer.invoke(CHANNELS.getMemory),
  saveMemory: (target, text, sessionId) =>
    ipcRenderer.invoke(CHANNELS.saveMemory, target, text, sessionId),
  forgetMemory: (target, entry, sessionId) =>
    ipcRenderer.invoke(CHANNELS.forgetMemory, target, entry, sessionId),
  rebuildSearchIndex: () => ipcRenderer.invoke(CHANNELS.rebuildSearchIndex),
  searchIndex: (query) => ipcRenderer.invoke(CHANNELS.searchIndex, query),
  getAutoCompact: () => ipcRenderer.invoke(CHANNELS.getAutoCompact),
  setAutoCompact: (settings) => ipcRenderer.invoke(CHANNELS.setAutoCompact, settings),
  getHelperModel: () => ipcRenderer.invoke(CHANNELS.getHelperModel),
  setHelperModel: (model) => ipcRenderer.invoke(CHANNELS.setHelperModel, model),
  getVisionModel: () => ipcRenderer.invoke(CHANNELS.getVisionModel),
  setVisionModel: (model) => ipcRenderer.invoke(CHANNELS.setVisionModel, model),
  getIslandSettings: () => ipcRenderer.invoke(CHANNELS.getIslandSettings),
  setIslandSettings: (settings) => ipcRenderer.invoke(CHANNELS.setIslandSettings, settings),
  listMcpServers: () => ipcRenderer.invoke(CHANNELS.listMcpServers),
  saveMcpServer: (id, cfg) => ipcRenderer.invoke(CHANNELS.saveMcpServer, id, cfg),
  removeMcpServer: (id) => ipcRenderer.invoke(CHANNELS.removeMcpServer, id),
  reconnectMcpServer: (id) => ipcRenderer.invoke(CHANNELS.reconnectMcpServer, id),
  listMcpPrompts: () => ipcRenderer.invoke(CHANNELS.listMcpPrompts),
  expandMcpPrompt: (server, name, args) =>
    ipcRenderer.invoke(CHANNELS.expandMcpPrompt, server, name, args),
  toolCatalog: () => ipcRenderer.invoke(CHANNELS.toolCatalog),
  listSubagents: (workspace) => ipcRenderer.invoke(CHANNELS.listSubagents, workspace),
  saveSubagent: (def, workspace) => ipcRenderer.invoke(CHANNELS.saveSubagent, def, workspace),
  createSubagent: (name, workspace) => ipcRenderer.invoke(CHANNELS.createSubagent, name, workspace),
  protocolListAdrs: (repoDir) => ipcRenderer.invoke(CHANNELS.protocolListAdrs, repoDir),
  protocolReadAdr: (repoDir, relPath) => ipcRenderer.invoke(CHANNELS.protocolReadAdr, repoDir, relPath),
  protocolListIssues: (repoDir) => ipcRenderer.invoke(CHANNELS.protocolListIssues, repoDir),
  protocolGetIssue: (repoDir, number) => ipcRenderer.invoke(CHANNELS.protocolGetIssue, repoDir, number),
  gitGraphLog: (repoDir, limit) => ipcRenderer.invoke(CHANNELS.gitGraphLog, repoDir, limit),
  gitGraphCommit: (repoDir, hash) => ipcRenderer.invoke(CHANNELS.gitGraphCommit, repoDir, hash),
  gitBranches: (repoDir) => ipcRenderer.invoke(CHANNELS.gitBranches, repoDir),
  gitCheckout: (repoDir, branch) => ipcRenderer.invoke(CHANNELS.gitCheckout, repoDir, branch),
  gitStatus: (repoDir) => ipcRenderer.invoke(CHANNELS.gitStatus, repoDir),
  setPresenceWorkspace: (repoDir) => ipcRenderer.invoke(CHANNELS.setPresenceWorkspace, repoDir),
  terminalList: (sessionId) => ipcRenderer.invoke(CHANNELS.terminalList, sessionId),
  terminalOpen: (sessionId, cols, rows) => ipcRenderer.invoke(CHANNELS.terminalOpen, sessionId, cols, rows),
  terminalAttach: (id) => ipcRenderer.invoke(CHANNELS.terminalAttach, id),
  terminalInput: (id, data) => ipcRenderer.invoke(CHANNELS.terminalInput, id, data),
  terminalResize: (id, cols, rows) => ipcRenderer.invoke(CHANNELS.terminalResize, id, cols, rows),
  terminalClose: (id) => ipcRenderer.invoke(CHANNELS.terminalClose, id),
  browserOpen: (sessionId) => ipcRenderer.invoke(CHANNELS.browserOpen, sessionId),
  browserNavigate: (sessionId, url) => ipcRenderer.invoke(CHANNELS.browserNavigate, sessionId, url),
  browserSetBounds: (sessionId, bounds) => ipcRenderer.invoke(CHANNELS.browserSetBounds, sessionId, bounds),
  browserBack: (sessionId) => ipcRenderer.invoke(CHANNELS.browserBack, sessionId),
  browserForward: (sessionId) => ipcRenderer.invoke(CHANNELS.browserForward, sessionId),
  browserReload: (sessionId) => ipcRenderer.invoke(CHANNELS.browserReload, sessionId),
  browserClose: (sessionId) => ipcRenderer.invoke(CHANNELS.browserClose, sessionId),
  intakePastedFiles: (files) => ipcRenderer.invoke(CHANNELS.intakePastedFiles, files),
  getAccount: () => ipcRenderer.invoke(CHANNELS.getAccount),
  walletBalance: () => ipcRenderer.invoke(CHANNELS.walletBalance),
  usageByProvider: (days: number) => ipcRenderer.invoke(CHANNELS.usageByProvider, days),
  providerBalances: () => ipcRenderer.invoke(CHANNELS.providerBalances),
  pokerTables: () => ipcRenderer.invoke(CHANNELS.pokerTables),
  pokerCreateTable: (input) => ipcRenderer.invoke(CHANNELS.pokerCreateTable, input),
  pokerJoin: (tableId, amount) => ipcRenderer.invoke(CHANNELS.pokerJoin, tableId, amount),
  pokerLeave: (tableId) => ipcRenderer.invoke(CHANNELS.pokerLeave, tableId),
  pokerStart: (tableId) => ipcRenderer.invoke(CHANNELS.pokerStart, tableId),
  pokerAct: (tableId, action) => ipcRenderer.invoke(CHANNELS.pokerAct, tableId, action),
  pokerWatch: (tableId) => ipcRenderer.invoke(CHANNELS.pokerWatch, tableId),
  signIn: (provider) => ipcRenderer.invoke(CHANNELS.signIn, provider),
  signOut: () => ipcRenderer.invoke(CHANNELS.signOut),
  myProfile: () => ipcRenderer.invoke(CHANNELS.myProfile),
  updateProfile: (patch) => ipcRenderer.invoke(CHANNELS.updateProfile, patch),
  keyStatus: () => ipcRenderer.invoke(CHANNELS.keyStatus),
  setApiKey: (envName, key) => ipcRenderer.invoke(CHANNELS.setApiKey, envName, key),
  openProviderConsole: (providerId) => ipcRenderer.invoke(CHANNELS.openProviderConsole, providerId),
  listOllamaModels: () => ipcRenderer.invoke(CHANNELS.listOllamaModels),
  sendMessage: (sessionId, text, skill, attachments, skillArgs) =>
    ipcRenderer.invoke(CHANNELS.sendMessage, sessionId, text, skill, attachments, skillArgs),
  pickAttachments: () => ipcRenderer.invoke(CHANNELS.pickAttachments),
  attachmentDataUrl: (id) => ipcRenderer.invoke(CHANNELS.attachmentDataUrl, id),
  stopTurn: (sessionId) => ipcRenderer.invoke(CHANNELS.stopTurn, sessionId),
  compact: (sessionId) => ipcRenderer.invoke(CHANNELS.compact, sessionId),
  decideApproval: (sessionId, toolCallId, outcome) =>
    ipcRenderer.invoke(CHANNELS.decideApproval, sessionId, toolCallId, outcome),
  answerQuestions: (sessionId, toolCallId, outcome) =>
    ipcRenderer.invoke(CHANNELS.answerQuestions, sessionId, toolCallId, outcome),
  onEvent: subscribe(CHANNELS.event),
  onApprovalRequest: subscribe(CHANNELS.approvalRequest),
  onAskUserRequest: subscribe(CHANNELS.askUserRequest),
  onTurnStatus: subscribe(CHANNELS.turnStatus),
  onAssistantDelta: subscribe(CHANNELS.assistantDelta),
  onToolOutput: subscribe(CHANNELS.toolOutput),
  onTerminalData: subscribe(CHANNELS.terminalData),
  onTerminalExit: subscribe(CHANNELS.terminalExit),
  onBrowserState: subscribe(CHANNELS.browserState),
  onMcpChanged: subscribe(CHANNELS.mcpChanged),
  onToolDefsChanged: subscribe(CHANNELS.toolDefsChanged),
  onAccountChanged: subscribe(CHANNELS.accountChanged),
  onPokerHand: subscribe(CHANNELS.pokerHand),
  onPokerError: subscribe(CHANNELS.pokerError),
  friendsSearch: (email) => ipcRenderer.invoke(CHANNELS.friendsSearch, email),
  friendsSendRequest: (userId) => ipcRenderer.invoke(CHANNELS.friendsSendRequest, userId),
  friendsRespond: (friendshipId, accept) =>
    ipcRenderer.invoke(CHANNELS.friendsRespond, friendshipId, accept),
  friendsRemove: (friendshipId) => ipcRenderer.invoke(CHANNELS.friendsRemove, friendshipId),
  friendsList: () => ipcRenderer.invoke(CHANNELS.friendsList),
  friendsSendMessage: (friendId, body) =>
    ipcRenderer.invoke(CHANNELS.friendsSendMessage, friendId, body),
  friendsListMessages: (friendId, beforeId) =>
    ipcRenderer.invoke(CHANNELS.friendsListMessages, friendId, beforeId),
  friendsSendInvite: (friendId, tableId, tableName) =>
    ipcRenderer.invoke(CHANNELS.friendsSendInvite, friendId, tableId, tableName),
  friendsRespondInvite: (inviteId, accept) =>
    ipcRenderer.invoke(CHANNELS.friendsRespondInvite, inviteId, accept),
  friendsCancelInvite: (inviteId) => ipcRenderer.invoke(CHANNELS.friendsCancelInvite, inviteId),
  friendsListInvites: () => ipcRenderer.invoke(CHANNELS.friendsListInvites),
  setBadgeCount: (count) => ipcRenderer.invoke(CHANNELS.setBadgeCount, count),
  onFriendsChanged: subscribe(CHANNELS.friendsChanged),
  onPresenceChanged: subscribe(CHANNELS.presenceChanged),
  onWorkspacesChanged: subscribe(CHANNELS.workspacesChanged),
  onDirectMessage: subscribe(CHANNELS.directMessage),
  onGameInvitesChanged: subscribe(CHANNELS.gameInvitesChanged),
  onRealtimeHealth: subscribe(CHANNELS.realtimeHealth),
  onNotificationActivated: subscribe(CHANNELS.notificationActivated),
  onIslandFocusSession: subscribe(CHANNELS.islandFocusSession),
  getWindowFullscreen: () => ipcRenderer.invoke(CHANNELS.getWindowFullscreen),
  onWindowFullscreen: subscribe(CHANNELS.windowFullscreen),
  setActiveSession: (sessionId) => ipcRenderer.invoke(CHANNELS.setActiveSession, sessionId),
};

contextBridge.exposeInMainWorld("otter", bridge);
